events {}

http {

    upstream sga_api {
        server sga-api-private-1:10000;
    }

    server {

        listen 10000;

        location /docs {
            return 404;
        }

        location /redoc {
            return 404;
        }

        location /openapi.json {
            return 404;
        }

        location /metrics {
            return 404;
        }

        location / {

            proxy_pass http://sga_api;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;
        }
    }
}