"""esquema inicial SGA

Revision ID: 095c30d34b56
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '095c30d34b56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edificios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('telefono_cifrado', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_correo'), 'personas', ['correo'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_qr', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('edificio_id', sa.Integer(), nullable=True),
    sa.Column('estatus_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion', sa.String(length=180), nullable=True),
    sa.Column('garantia', sa.String(length=120), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['edificio_id'], ['edificios.id'], ),
    sa.ForeignKeyConstraint(['estatus_id'], ['estatus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_index(op.f('ix_activos_codigo_qr'), 'activos', ['codigo_qr'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('creada_por_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_cancelacion', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorias_estado'), 'auditorias', ['estado'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti_hash'), 'refresh_tokens', ['jti_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('detalle_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditoria_id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('estado_revision', sa.String(length=30), nullable=False),
    sa.Column('encontrado', sa.Boolean(), nullable=True),
    sa.Column('estatus_anterior_id', sa.Integer(), nullable=True),
    sa.Column('estatus_nuevo_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_encontrada', sa.String(length=180), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('tipo_incidencia', sa.String(length=60), nullable=True),
    sa.Column('revisado_por_id', sa.Integer(), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['estatus_anterior_id'], ['estatus.id'], ),
    sa.ForeignKeyConstraint(['estatus_nuevo_id'], ['estatus.id'], ),
    sa.ForeignKeyConstraint(['revisado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auditoria_id', 'activo_id', name='uq_auditoria_activo')
    )
    op.create_index(op.f('ix_detalle_auditoria_estado_revision'), 'detalle_auditoria', ['estado_revision'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=80), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['detalle_id'], ['detalle_auditoria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_detalle_id'), 'evidencias', ['detalle_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidencias_detalle_id'), table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_detalle_auditoria_estado_revision'), table_name='detalle_auditoria')
    op.drop_table('detalle_auditoria')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_auditorias_estado'), table_name='auditorias')
    op.drop_table('auditorias')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_activos_codigo_qr'), table_name='activos')
    op.drop_table('activos')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_personas_correo'), table_name='personas')
    op.drop_table('personas')
    op.drop_table('estatus')
    op.drop_table('edificios')
    # ### end Alembic commands ###
